CREATE DATABASE IF NOT EXISTS bluphy;

USE bluphy;

CREATE TABLE locdev (
id INT(3) NOT NULL PRIMARY KEY,
dev VARCHAR(50) NOT NULL,
mac VARCHAR(18) NOT NULL
);

CREATE TABLE dev (
id INT(3) NOT NULL PRIMARY KEY,
dev VARCHAR(50) NOT NULL,
mac VARCHAR(18) NOT NULL
);