CREATE DATABASE IF NOT EXISTS bluphy;

USE bluphy;

CREATE TABLE locdev (
id INT(3) NOT NULL PRIMARY KEY,
dev VARCHAR(50) NOT NULL,
mac VARCHAR(18) NOT NULL
);

CREATE TABLE dev (
id INT(3) NOT NULL PRIMARY KEY,
dev VARCHAR(50) NOT NULL,
mac VARCHAR(18) NOT NULL
);

CREATE TABLE active (
id INT(2) NOT NULL PRIMARY KEY,
tx VARCHAR(18),
rx VARCHAR(18),
port INT(2),
msg VARCHAR(100)
);

INSERT INTO active (id) VALUES (0);